### ISSUE TITLE
Support Classes

### ISSUE THREAD

**Issue by LeanKhan** [hapy-lang/hapy#8]
Let users create classes, but using simpler syntax.

**Comment by LeanKhan** [comment]
Hey guys @alummav @Shugaba-Wuta . I want to share the design of Hapy Classes I had in mind... So this is how I propose a class may be defined and how it may be transpiled as well as possible tokens generated.

**Syntax in (English) Hapy**

```
class Classname {

    # -- class properties --
    has property_1;
    has property_2 = 20;
  
   # -- class methods --
   can do_something(args) {
      # do stuff
    }

    can do_anotherthing(args) {
         # do stuff
        self.name;
        self.do_something(args);  
    }
}
```

**Generated Python**
```
class Classname:

  def __init__(self, property_1):
        self.property_1 = property_1;
        self.property_2 = 20;
  
   # -- class methods --
   def do_something(self, args):
      # do stuff

    def do_anotherthing(self, args):
         # do stuff
        self.name;
        self.do_something(args);  # stays the same

```

**Possible token structure**
_Tokens should give enough information about the class_

```
type: class,
name: (name of class, just a string),
parent*: (var token since it's just a name we need) or None
properties: (List of class_prop tokens)
    | type: class_property
    | name: (name of the property)
    | default: (default value: any other token or None)

methods: (List of class_method tokens, very similar to the func token)
    | type: class_method
    | name: (name of the method)
    | args: (method arguments)
    | body: (other tokens)
```

Please what do you think, share in the comments so we have this documented.

**Comment by Shugaba-Wuta** [comment]
That means all methods will be instance methods, no class methods right?Sent from my Galaxy

**Comment by LeanKhan** [comment]
Yes, only instnace methods. Class methods can also have their own syntax
but I didn't think of those

**Comment by Shugaba-Wuta** [comment]
So how do you call this class then, because passing attributes should be possible right?Sent from my Galaxy

**Comment by LeanKhan** [comment]
Sorry for late response, I was thinking we can invoke the class like:
`bola = new Boy(name="Bola",age=20)` or `bola = a Boy(name="Bola",age=20)`
What do you think?

**Comment by LeanKhan** [comment]
Lemme add one for inheritance...

```python
class Child [from/extends] Parent {

    # -- class properties --
    has property_1;
    has property_2 = 20;
  
   # -- class methods --
   can do_something(args) {
      # do stuff
    }

    can do_anotherthing(args) {
         # do stuff
        self.name;
        self.do_something(args);  
    }
}
```

This is similar to JS/TS syntax for class inheritance. Thoughts? @Shugaba-Wuta

**Comment by Shugaba-Wuta** [comment]
That means there is support for only one inheritance?

**Comment by LeanKhan** [comment]
Yeahh, we can add more too.
